### PR TITLE
Drop escape binding, code cleanup

### PR DESCRIPTION
**Pull request by clayreimann**
I realize that #36 was caused by a bad native compilation but it seems that it would be better if `git-diff-details` didn't have to bind the `esc` key directly (`find-and-replace` doesn't).

Also I tweaked how repos are looked up to be [compatible with `2.x`](https://atom.io/docs/api/v1.2.0/Project#instance-getRepositories) whenever that drops

### CODE REVIEW

**Comment by samu** [comment]
Thanks for the PR. Does this remove the escape functionality completely, or is it replaced with a different implementation?

**Comment by clayreimann** [comment]
It tracks the `core:cancel` event which the editor emits when the `esc` key is pressed. (Similar to what the `find-and-replace` package does)

**Comment by samu** [comment]
Awesome! I didn't know about that. 

Thanks! I'll pull as soon as i can, please note i'm a bit busy atm :construction_worker:

**Comment by clayreimann** [comment]
No worries

**Comment by samu** [comment]
Ok so i took a look at this and i have a couple of concerns:

1. There seems to be a bug. When i close a tab, i get this error:

  `Uncaught TypeError: disposable.dispose is not a function`

2. I don't agree with the refactoring. Is there a specific reason why you removed `housekeeping.coffee` and put it in to `git-diff-details-view.coffee`? Having that code in a separate file seems much cleaner to me.

3. There's a log statement printing `initializing`. That certainly shouldn't be there.

Please fix these and i'll merge. Thank you very much :smiley_cat:

**Comment by samu** [comment]
Closing this in favor of 36c1c2f.

Thanks for your inputs, this was very helpful.

**Pull request closed without merging**
