### PR TITLE
Show word diffs

### PR DESCRIPTION
**Pull request by itiut**
Show word diffs when the length of new lines is same as old lines.

### CODE REVIEW

**Comment by xdmx** [comment]
Awesome, why limiting it to just when the length of lines are the same?
This is how Rubymine shows the diff (in the version control view diff, not in the text view diff)

screenshot_20160415_121733

**Comment by samu** [comment]
@itiut i think this isn't working properly yet

screen shot 2016-04-16 at 13 19 32

**Comment by itiut** [comment]
@samu I fixed the bug.

@xdmx Because I think it is hard for me to get word diffs nicely by comparing lines and other lines which length is not the same. If so, word highlights are too bright to see when there are many changes.

**Comment by samu** [comment]
@itiut Perfect! Thanks a lot for your hard work 👷

**Comment by samu** [comment]
released in `1.3.0`

**Pull request merged**
