### PR TITLE
Fix https://github.com/samu/git-diff-details/issues/22

### PR DESCRIPTION
**Pull request by Evmorov**
A very annoying bug. I think it was just a typo.

### CODE REVIEW

**Comment by samu** [comment]
@Evmorov Thanks. Did you test this? If i remember correctly i already tried this, which resulted in an other error :( 

I'm pretty busy right now and can't guarantee that this will be fixed soon. If you want to help out, you can look at [this file from the atom git-diff package](https://github.com/atom/git-diff/blob/a4b85b353b96840500ee9d783fcd78b8ac5d4fa0/lib/git-diff-view.coffee) - i copied most of the code for subscriptions from there and modified it to my needs...

**Comment by Evmorov** [comment]
@samu I didn't dig into your code but for me it works perfectly (add/remove project with/without git repository). Tomorrow I will check it on Windows (now I'm on mac) and will write here.

**Comment by Evmorov** [comment]
@samu can't check it on Windows because of https://github.com/samu/git-diff-details/issues/23

**Comment by Evmorov** [comment]
I've managed to install this package on Windows and with this small change it works perfectly.

**Comment by samu** [comment]
@Evmorov Thanks!

**Pull request merged**
