### PR TITLE
Use Atom's TextEditor and its view to display old versions

### LINKED ISSUE #48: Incorrect tab width in diffs
I'm writing in golang which uses tabs, but the tabs are being rendered in the diff with my preferred tab-width.

### PR DESCRIPTION
**Pull request by itiut**
Using Atom's `TextEditor` class and its view, we can do following things:

- Hard tabs are displayed with correct width. Fix #48.
- Syntax highlighting is enabled.
- Text is selectable (#30).

I am planning to implement word-by-word diffs, and this also makes highlighting words easier in the diff view via Decoration API.

### CODE REVIEW

**Comment by samu** [comment]
Thanks, this is awesome! I tried it out and it seems to work really well, though i'd like to explore a little bit on the following:

1) I think the currently selected line should not be highlighted. When looking at a diff, we don't want to know on which line we are. Both the green and the red part should not highlight the selected line. Currently, it looks like this (We only see two lines in green and two lines in red, though we should see three lines in green and three lines in red):

screen shot 2016-04-01 at 16 58 29

2) Scrolling of the red part should be disabled, as it leads to weird behaviour:
abc

3) It would be really great if it was possible to configure whether the diffs should be highlighted or not. I actually did not highlight the diffs on purpose, because i dont think it is important, as git diffs tend to be small and hence highlighting isn't necessary or even distracting.

It'd be really great if these details were addressed.

**Comment by itiut** [comment]
Thanks for reviewing.

1) I didn't notice that the current line is highlighted because I use the syntax theme that doesn't highlight the current line. So I fixed it.

2) Hmm... this behaviour doesn't seem to happen in my environment (Atom 1.6.2 on OS X). I will examine it on this and other environments, so could you tell me your environment?

3) OK, I will make an option to enable syntax highlighting in the diffs.

**Comment by samu** [comment]
I have the same environment. I can imagine it has to do with the _Scroll Past End_ setting. I have enabled that. I assume you'll be able to fix the scrolling problem by passing `scrollPastEnd: false` when initializing the editor element :)

**Comment by itiut** [comment]
Thanks! I reproduced the scrolling problem by enabling *Scroll Past End*, and fixed it on Atom 1.7.0-beta4. Passing `scrollPastEnd: false` is effective on v1.7.0-beta0 or higher, not on v1.6.2.

I added an option to toggle syntax highliginting in diff view.

**Comment by samu** [comment]
Great work, thanks! :tada: :boom:

**Pull request merged**
